<a href="https://colab.research.google.com/github/shubhamarora03/Deep_Learning/blob/master/EntityEmbedding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [0]:
import pandas as pd
import numpy as np
from sklearn import preprocessing

In [0]:
import tensorflow as tf
from tensorflow.keras import layers
from tensorflow.keras import optimizers
from tensorflow.keras.models import Model

In [0]:
train=pd.read_csv("./drive/My Drive/Data/train.csv")
test =pd.read_csv("./drive/My Drive/Data/test.csv")

In [4]:
train.target.unique()

array([0, 1])

In [5]:
train.head()

id  bin_0  bin_1  bin_2 bin_3 bin_4  ... ord_3 ord_4 ord_5  day month target
0   0    0.0    0.0    0.0     F     N  ...     c     U    Pw  6.0   3.0      0
1   1    1.0    1.0    0.0     F     Y  ...     e     X    pE  7.0   7.0      0
2   2    0.0    1.0    0.0     F     N  ...     n     P    eN  5.0   9.0      0
3   3    NaN    0.0    0.0     F     N  ...     a     C   NaN  3.0   3.0      0
4   4    0.0    NaN    0.0     T     N  ...     h     C    OZ  5.0  12.0      0

[5 rows x 25 columns]

In [0]:
test['target']=-1

In [7]:
test.head()

id  bin_0  bin_1  bin_2 bin_3  ... ord_4 ord_5  day month target
0  600000    0.0    0.0    0.0     F  ...     U    oU  3.0   9.0     -1
1  600001    0.0    0.0    0.0     F  ...     N   NaN  2.0   8.0     -1
2  600002    0.0    0.0    0.0     F  ...     N    DN  2.0   6.0     -1
3  600003    1.0    0.0    0.0     F  ...     B    AG  1.0   6.0     -1
4  600004    0.0    0.0    1.0     F  ...     J    DT  3.0   3.0     -1

[5 rows x 25 columns]

In [8]:
train.shape , test.shape

((600000, 25), (400000, 25))

In [0]:
full_data = pd.concat([train,test]).reset_index(drop=True)

In [10]:
full_data.shape

(1000000, 25)

In [0]:
features=[f for f in train.columns if f not in ["id","target"]]

In [12]:
features

['bin_0',
 'bin_1',
 'bin_2',
 'bin_3',
 'bin_4',
 'nom_0',
 'nom_1',
 'nom_2',
 'nom_3',
 'nom_4',
 'nom_5',
 'nom_6',
 'nom_7',
 'nom_8',
 'nom_9',
 'ord_0',
 'ord_1',
 'ord_2',
 'ord_3',
 'ord_4',
 'ord_5',
 'day',
 'month']

In [0]:
for col in features:
  full_data.loc[:,col]=full_data.loc[:,col].astype(str).fillna("-1")

In [14]:
full_data.target.unique()

array([ 0,  1, -1])

In [0]:
for col in features:
  lbl_enc = preprocessing.LabelEncoder()
  full_data.loc[:,col] = lbl_enc.fit_transform(full_data[col])

In [0]:
full_data.head()

id  bin_0  bin_1  bin_2  bin_3  ...  ord_4  ord_5  day  month  target
0   0      0      0      0      0  ...     20     56    5      5       0
1   1      1      1      0      0  ...     23    151    6      9       0
2   2      0      1      0      0  ...     15    105    4     11       0
3   3      2      0      0      0  ...      2    140    2      5       0
4   4      0      2      0      1  ...      2     50    4      3       0

[5 rows x 25 columns]

In [0]:
train = full_data[full_data.target!=-1].reset_index(drop=True)
test  = full_data[full_data.target==-1].reset_index(drop=True)

In [17]:
train.shape , test.shape

((600000, 25), (400000, 25))

In [18]:
int(min(np.ceil(1000/2),50))

50

Converting list of list of features

In [0]:
def get_model(df,columns):
  inputs=[]
  outputs=[]
  for c in columns:
    num_uniq_values=int(df[c].nunique())
    emb_dim = int(min(np.ceil(num_uniq_values/2),50))
    #One embedding layer for each variable
    inp = layers.Input(shape=(1,))
    out = layers.Embedding(num_uniq_values+1,emb_dim)(inp)
    out = layers.Reshape(target_shape=(emb_dim,))(out)
    #Appending all the categorical inputs
    inputs.append(inp)
    #Appending all the embeddings
    outputs.append(out)
  x = layers.Concatenate()(outputs)
  x = layers.Dense(300,activation='relu')(x)
  x = layers.Dropout(0.3) (x)
  y = layers.Dense(1,activation='sigmoid')(x)
  model = Model(inputs=inputs,outputs=y)
  return model

In [20]:
get_model(train,features).summary()

Model: "model"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_1 (InputLayer)            [(None, 1)]          0                                            
__________________________________________________________________________________________________
input_2 (InputLayer)            [(None, 1)]          0                                            
__________________________________________________________________________________________________
input_3 (InputLayer)            [(None, 1)]          0                                            
__________________________________________________________________________________________________
input_4 (InputLayer)            [(None, 1)]          0                                            
______________________________________________________________________________________________

In [0]:
model = get_model(train,features)
model.compile(loss='binary_crossentropy',optimizer='adam', metrics=['accuracy'])

In [0]:
[train.head(10).loc[:,f].values for f in features]

[array([0, 1, 0, 2, 0, 0, 0, 0, 0, 0]),
 array([0, 1, 1, 0, 2, 2, 0, 0, 0, 0]),
 array([0, 0, 0, 0, 0, 1, 0, 1, 0, 2]),
 array([0, 0, 0, 0, 1, 1, 0, 1, 0, 0]),
 array([0, 1, 0, 0, 0, 0, 0, 0, 0, 1]),
 array([2, 2, 2, 2, 2, 2, 2, 2, 0, 2]),
 array([4, 3, 6, 0, 5, 5, 5, 5, 1, 1]),
 array([3, 0, 3, 3, 3, 4, 3, 0, 3, 3]),
 array([5, 6, 0, 3, 2, 1, 2, 3, 5, 3]),
 array([0, 3, 0, 3, 4, 0, 0, 0, 1, 3]),
 array([1059,  210,  860,  477,  556,  766,  645,   83,    6,  754]),
 array([1013,  359,  694,  241,  361, 1059, 1222,  277, 1003, 1387]),
 array([ 87,  27,  90,  51, 182, 138,  25, 124,  64,  84]),
 array([  1,  69, 102, 170, 222,  93, 167, 169, 138,   2]),
 array([  27, 2112, 2218, 2167, 1747,   59,  692, 1464, 2218, 1086]),
 array([2, 2, 2, 0, 2, 1, 0, 2, 0, 2]),
 array([0, 2, 5, 4, 2, 1, 2, 1, 4, 0]),
 array([3, 5, 2, 4, 1, 3, 1, 1, 0, 4]),
 array([ 2,  4, 13,  0,  7,  1,  2,  1,  2, 13]),
 array([20, 23, 15,  2,  2, 16, 17, 24, 13,  8]),
 array([ 56, 151, 105, 140,  50, 181, 159,  54, 13

In [23]:
model.fit([train.loc[:,f].values for f in features],
          train.target.values,
          batch_size=64,
          epochs=5)

Epoch 1/5
9375/9375 [==============================] - 89s 9ms/step - loss: 0.3925 - accuracy: 0.8293
Epoch 2/5
9375/9375 [==============================] - 88s 9ms/step - loss: 0.3801 - accuracy: 0.8353
Epoch 3/5
9375/9375 [==============================] - 88s 9ms/step - loss: 0.3666 - accuracy: 0.8431
Epoch 4/5
9375/9375 [==============================] - 86s 9ms/step - loss: 0.3522 - accuracy: 0.8500
Epoch 5/5
9375/9375 [==============================] - 86s 9ms/step - loss: 0.3374 - accuracy: 0.8570
